export const LANGUAGES = [
    { label: "English", value: "en" },
    { label: "Hindi", value: "hi" },
]

export const fieldsOfStudy = [
    { value: "Engineering", label: "Engineering" },
    { value: "Civil Engineering", label: "Civil Engineering" },
    { value: "Mechanical Engineering", label: "Mechanical Engineering" },
    { value: "Electrical Engineering", label: "Electrical Engineering" },
    { value: "Chemical Engineering", label: "Chemical Engineering" },
    { value: "Aerospace Engineering", label: "Aerospace Engineering" },
    { value: "Computer Engineering", label: "Computer Engineering" },
    { value: "Industrial Engineering", label: "Industrial Engineering" },
    { value: "Environmental Engineering", label: "Environmental Engineering" },
    { value: "Biomedical Engineering", label: "Biomedical Engineering" },
    { value: "Agricultural Engineering", label: "Agricultural Engineering" },

    { value: "Medicine & Health Sciences", label: "Medicine & Health Sciences" },
    { value: "General Medicine", label: "General Medicine" },
    { value: "Surgery", label: "Surgery" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Obstetrics & Gynecology", label: "Obstetrics & Gynecology" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Dentistry", label: "Dentistry" },
    { value: "Nursing", label: "Nursing" },
    { value: "Public Health", label: "Public Health" },
    { value: "Pharmacology", label: "Pharmacology" },
    { value: "Veterinary Medicine", label: "Veterinary Medicine" },
    { value: "Physiotherapy", label: "Physiotherapy" },
    { value: "Radiology", label: "Radiology" },
    { value: "Optometry", label: "Optometry" },

    { value: "Law", label: "Law" },
    { value: "Criminal Law", label: "Criminal Law" },
    { value: "Corporate Law", label: "Corporate Law" },
    { value: "Civil Law", label: "Civil Law" },
    { value: "International Law", label: "International Law" },
    { value: "Family Law", label: "Family Law" },
    { value: "Environmental Law", label: "Environmental Law" },
    { value: "Tax Law", label: "Tax Law" },
    { value: "Intellectual Property Law", label: "Intellectual Property Law" },
    { value: "Labor Law", label: "Labor Law" },
    { value: "Constitutional Law", label: "Constitutional Law" },

    { value: "Business & Management", label: "Business & Management" },
    { value: "Business Administration", label: "Business Administration" },
    { value: "Marketing", label: "Marketing" },
    { value: "Finance", label: "Finance" },
    { value: "Accounting", label: "Accounting" },
    { value: "Human Resources", label: "Human Resources" },
    { value: "Supply Chain Management", label: "Supply Chain Management" },
    { value: "Management Information Systems", label: "Management Information Systems" },
    { value: "Entrepreneurship", label: "Entrepreneurship" },
    { value: "International Business", label: "International Business" },
    { value: "Organizational Behavior", label: "Organizational Behavior" },

    { value: "Computer Science & Information Technology", label: "Computer Science & IT" },
    { value: "Software Engineering", label: "Software Engineering" },
    { value: "Data Science", label: "Data Science" },
    { value: "Artificial Intelligence", label: "Artificial Intelligence" },
    { value: "Machine Learning", label: "Machine Learning" },
    { value: "Cybersecurity", label: "Cybersecurity" },
    { value: "Information Systems", label: "Information Systems" },
    { value: "Web Development", label: "Web Development" },
    { value: "Cloud Computing", label: "Cloud Computing" },
    { value: "Computer Networks", label: "Computer Networks" },
    { value: "Computer Graphics", label: "Computer Graphics" },

    { value: "Social Sciences", label: "Social Sciences" },
    { value: "Psychology", label: "Psychology" },
    { value: "Sociology", label: "Sociology" },
    { value: "Political Science", label: "Political Science" },
    { value: "Anthropology", label: "Anthropology" },
    { value: "Economics", label: "Economics" },
    { value: "Geography", label: "Geography" },
    { value: "Criminology", label: "Criminology" },
    { value: "International Relations", label: "International Relations" },
    { value: "Social Work", label: "Social Work" },
    { value: "Human Rights", label: "Human Rights" },

    { value: "Humanities", label: "Humanities" },
    { value: "History", label: "History" },
    { value: "Philosophy", label: "Philosophy" },
    { value: "Literature", label: "Literature" },
    { value: "Linguistics", label: "Linguistics" },
    { value: "Religious Studies", label: "Religious Studies" },
    { value: "Cultural Studies", label: "Cultural Studies" },
    { value: "Art History", label: "Art History" },
    { value: "Political Philosophy", label: "Political Philosophy" },
    { value: "Comparative Literature", label: "Comparative Literature" },

    { value: "Natural Sciences", label: "Natural Sciences" },
    { value: "Biology", label: "Biology" },
    { value: "Chemistry", label: "Chemistry" },
    { value: "Physics", label: "Physics" },
    { value: "Geology", label: "Geology" },
    { value: "Astronomy", label: "Astronomy" },
    { value: "Environmental Science", label: "Environmental Science" },
    { value: "Oceanography", label: "Oceanography" },
    { value: "Ecology", label: "Ecology" },
    { value: "Meteorology", label: "Meteorology" },
    { value: "Genetics", label: "Genetics" },

    { value: "Mathematics & Statistics", label: "Mathematics & Statistics" },
    { value: "Pure Mathematics", label: "Pure Mathematics" },
    { value: "Applied Mathematics", label: "Applied Mathematics" },
    { value: "Statistics", label: "Statistics" },
    { value: "Actuarial Science", label: "Actuarial Science" },
    { value: "Computational Mathematics", label: "Computational Mathematics" },
    { value: "Mathematical Finance", label: "Mathematical Finance" },
    { value: "Operations Research", label: "Operations Research" },

    { value: "Education", label: "Education" },
    { value: "Early Childhood Education", label: "Early Childhood Education" },
    { value: "Special Education", label: "Special Education" },
    { value: "Higher Education", label: "Higher Education" },
    { value: "Educational Leadership", label: "Educational Leadership" },
    { value: "Curriculum and Instruction", label: "Curriculum and Instruction" },
    { value: "Educational Psychology", label: "Educational Psychology" },
    { value: "Instructional Technology", label: "Instructional Technology" },
];

export const degreesList = [
    { value: "History", label: "Bachelor of Arts (BA) in History" },
    { value: "Philosophy", label: "Bachelor of Arts (BA) in Philosophy" },
    { value: "English Literature", label: "Master of Arts (MA) in English Literature" },
    { value: "Anthropology", label: "Doctor of Philosophy (PhD) in Anthropology" },
    { value: "Graphic Design", label: "Bachelor of Fine Arts (BFA) in Graphic Design" },

    { value: "Business Administration", label: "Bachelor of Business Administration (BBA)" },
    { value: "Business Administration", label: "Master of Business Administration (MBA)" },
    { value: "Management", label: "Master of Science in Management (MSc)" },
    { value: "Business Administration", label: "Doctor of Business Administration (DBA)" },

    { value: "Computer Science", label: "Bachelor of Science (BS) in Computer Science" },
    { value: "Artificial Intelligence", label: "Master of Science (MS) in Artificial Intelligence" },
    { value: "Data Science", label: "Doctor of Philosophy (PhD) in Data Science" },
    { value: "Software Engineering", label: "Bachelor of Science (BS) in Software Engineering" },
    { value: "Information Technology", label: "Master of Information Technology (MIT)" },

    { value: "Civil Engineering", label: "Bachelor of Engineering (BEng) in Civil Engineering" },
    { value: "Electrical Engineering", label: "Master of Science (MS) in Electrical Engineering" },
    { value: "Mechanical Engineering", label: "Doctor of Philosophy (PhD) in Mechanical Engineering" },
    { value: "Chemical Engineering", label: "Bachelor of Science (BS) in Chemical Engineering" },

    { value: "Medicine", label: "Bachelor of Medicine, Bachelor of Surgery (MBBS)" },
    { value: "Medicine", label: "Doctor of Medicine (MD)" },
    { value: "Public Health", label: "Master of Public Health (MPH)" },
    { value: "Nursing", label: "Master of Science (MS) in Nursing" },
    { value: "Biochemistry", label: "Bachelor of Science (BS) in Biochemistry" },

    { value: "Education", label: "Bachelor of Education (BEd)" },
    { value: "Education", label: "Master of Education (MEd)" },
    { value: "Education", label: "Doctor of Education (EdD)" },
    { value: "Early Childhood Education", label: "Bachelor of Science (BS) in Early Childhood Education" },

    { value: "Law", label: "Bachelor of Laws (LLB)" },
    { value: "Law", label: "Master of Laws (LLM)" },
    { value: "Law", label: "Doctor of Juridical Science (SJD)" },
    { value: "Political Science", label: "Bachelor of Arts (BA) in Political Science" },

    { value: "Sociology", label: "Bachelor of Arts (BA) in Sociology" },
    { value: "Psychology", label: "Master of Science (MS) in Psychology" },
    { value: "Social Work", label: "Master of Social Work (MSW)" },
    { value: "Economics", label: "Doctor of Philosophy (PhD) in Economics" },

    { value: "Physics", label: "Bachelor of Science (BS) in Physics" },
    { value: "Chemistry", label: "Bachelor of Science (BS) in Chemistry" },
    { value: "Biology", label: "Master of Science (MS) in Biology" },
    { value: "Environmental Science", label: "Doctor of Philosophy (PhD) in Environmental Science" },

    { value: "Architecture", label: "Bachelor of Architecture (BArch)" },
    { value: "Architecture", label: "Master of Architecture (MArch)" },
    { value: "Interior Design", label: "Master of Fine Arts (MFA) in Interior Design" },
    { value: "Urban Planning", label: "Bachelor of Science (BS) in Urban Planning" },

    { value: "French Literature", label: "Bachelor of Arts (BA) in French Literature" },
    { value: "Linguistics", label: "Master of Arts (MA) in Linguistics" },
    { value: "Comparative Literature", label: "Doctor of Philosophy (PhD) in Comparative Literature" },

    { value: "Journalism", label: "Bachelor of Arts (BA) in Journalism" },
    { value: "Public Relations", label: "Master of Arts (MA) in Public Relations" },
    { value: "Media Studies", label: "Bachelor of Arts (BA) in Media Studies" },

    { value: "Agricultural Science", label: "Bachelor of Science (BS) in Agricultural Science" },
    { value: "Environmental Studies", label: "Master of Science (MS) in Environmental Studies" },
    { value: "Forestry", label: "Doctor of Philosophy (PhD) in Forestry" },

    { value: "Dance", label: "Bachelor of Fine Arts (BFA) in Dance" },
    { value: "Theater", label: "Master of Fine Arts (MFA) in Theater" },
    { value: "Music Performance", label: "Bachelor of Music (BM) in Music Performance" },
    { value: "Composition", label: "Master of Music (MM) in Composition" },

    { value: "Hospitality Management", label: "Bachelor of Science (BS) in Hospitality Management" },
    { value: "Tourism Management", label: "Master of Science (MS) in Tourism Management" },

    { value: "Economics", label: "Bachelor of Science (BS) in Economics" },
    { value: "Finance", label: "Master of Science (MS) in Finance" },
    { value: "Finance", label: "Master of Business Administration (MBA) in Finance" }
];

